"""tfmx.qsrs - Qwen3-ASR serving via unified qsr CLI."""

from .benchmark import ASRBenchmarkMetrics
from .benchmark import QSRBenchmark
from .client import AsyncQSRClient
from .client import ChatChoice
from .client import ChatMessage
from .client import ChatResponse
from .client import ChatUsage
from .client import HealthResponse
from .client import InfoResponse
from .client import InstanceInfo
from .client import MachineStats
from .client import ModelInfo
from .client import QSRClient
from .client import StreamChatResult
from .client import TranscriptionResponse
from .client import build_audio_messages
from .client import build_text_messages
from .client import format_elapsed_time
from .client import format_stream_stats_line
from .client import join_prompt_texts
from .client import normalize_audio_url
from .clients import QSRClients
from .clients_core import ClientsHealthResponse
from .clients_core import MachineScheduler
from .clients_core import MachineState
from .clients_stats import QSRClientsWithStats
from .long_audio import AudioChunk
from .long_audio import AudioMetadata
from .long_audio import ChunkTranscriptionResult
from .long_audio import LongAudioTranscriber
from .long_audio import LongAudioTranscriptionConfig
from .long_audio import LongAudioTranscriptionResult
from .long_audio import SilenceRegion
from .compose import ComposeFileGenerator
from .compose import DockerImageManager
from .compose import GPUDetector
from .compose import GPUInfo
from .compose import GPU_LAYOUT_UNIFORM
from .compose import GpuModelConfig
from .compose import MACHINE_PORT
from .compose import MODEL_NAME
from .compose import MODEL_SHORTCUTS
from .compose import ModelConfigManager
from .compose import QSRComposer
from .compose import SERVER_PORT
from .compose import SUPPORTED_MODELS
from .compose import VLLM_BASE_IMAGE
from .compose import VLLM_IMAGE
from .compose import VLLM_INTERNAL_PORT
from .compose import build_gpu_configs_for_layout
from .compose import get_model_api_aliases
from .compose import get_model_shortcut
from .compose import infer_gpu_ids
from .compose import normalize_model_key
from .compose import parse_gpu_configs
from .compose import resolve_model_name
from .machine import ChatCompletionRequest
from .machine import HealthResponse as MachineHealthResponse
from .machine import InfoResponse as MachineInfoResponse
from .machine import ModelsResponse
from .machine import QSRInstance
from .machine import QSRInstanceDiscovery
from .machine import QSRMachineDaemon
from .machine import QSRMachineServer
from .networking import DEFAULT_HF_ENDPOINT
from .networking import DEFAULT_PIP_INDEX_URL
from .networking import DEFAULT_PIP_TRUSTED_HOST
from .networking import QSRNetworkConfig
from .networking import detect_default_proxy
from .networking import is_loopback_proxy
from .perf_tracker import PerfTracker
from .perf_tracker import RoundContext
from .perf_tracker import RoundRecord
from .perf_tracker import TaskContext
from .perf_tracker import TaskRecord
from .perf_tracker import WorkerEvent
from .perf_tracker import WorkerStats
from .perf_tracker import get_global_tracker
from .perf_tracker import reset_global_tracker
from .performance import ExplorationConfig
from .performance import ExplorationState
from .performance import PerformanceMetrics
from .performance import PerformanceTracker
from .router import InstanceDescriptor
from .router import QSRRouter
from .router import parse_model_spec
from .scheduler import DistributionResult
from .scheduler import IdleFillingScheduler
from .scheduler import MAX_CLIENT_BATCH_SIZE
from .scheduler import WorkerState
from .scheduler import distribute_with_adaptive_pipeline
